/*
 * This source file was generated by the Gradle 'init' task
 */
package numer0n;
import numer0n.service.GameManager;
import numer0n.service.impl.GameManagerImpl;

public class App {

    public static void main(String[] args) {
        // ゲームを開始
           GameManager gamemanager = new GameManagerImpl();
           gamemanager.start();
    }
}
